//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyDesignApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class StringSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StringSettings defaultInstance = ((StringSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StringSettings())));
        
        public static StringSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position Definitions")]
        public string Header_PositionDefinitionsPanel {
            get {
                return ((string)(this["Header_PositionDefinitionsPanel"]));
            }
            set {
                this["Header_PositionDefinitionsPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stimulus Definitions")]
        public string Header_StimulusDefinitionsPanel {
            get {
                return ((string)(this["Header_StimulusDefinitionsPanel"]));
            }
            set {
                this["Header_StimulusDefinitionsPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Add Image Stimulus")]
        public string Tooltip_AddImageStimulusButton {
            get {
                return ((string)(this["Tooltip_AddImageStimulusButton"]));
            }
            set {
                this["Tooltip_AddImageStimulusButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Add Point Position")]
        public string Tooltip_AddPointPositionButton {
            get {
                return ((string)(this["Tooltip_AddPointPositionButton"]));
            }
            set {
                this["Tooltip_AddPointPositionButton"] = value;
            }
        }
    }
}
