//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyDesignApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class ValueSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ValueSettings defaultInstance = ((ValueSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ValueSettings())));
        
        public static ValueSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double DefinitionsPanelWidth {
            get {
                return ((double)(this["DefinitionsPanelWidth"]));
            }
            set {
                this["DefinitionsPanelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double BlockDesignPanelWidth {
            get {
                return ((double)(this["BlockDesignPanelWidth"]));
            }
            set {
                this["BlockDesignPanelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double SplitterWidth {
            get {
                return ((double)(this["SplitterWidth"]));
            }
            set {
                this["SplitterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double HeaderHeight {
            get {
                return ((double)(this["HeaderHeight"]));
            }
            set {
                this["HeaderHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double EdgeThickness {
            get {
                return ((double)(this["EdgeThickness"]));
            }
            set {
                this["EdgeThickness"] = value;
            }
        }
    }
}
