//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyDesignStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurPsyDesignStrings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Design Window.
        /// </summary>
        public static string DesignWindowTitle {
            get {
                return ResourceManager.GetString("DesignWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Definitions.
        /// </summary>
        public static string ElementsPanelHeader {
            get {
                return ResourceManager.GetString("ElementsPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HurPsy Experiment Files (*.xml) |*.xml.
        /// </summary>
        public static string ExperimentFileFilter {
            get {
                return ResourceManager.GetString("ExperimentFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Experiment.
        /// </summary>
        public static string ExperimentMenuHeader {
            get {
                return ResourceManager.GetString("ExperimentMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Blocks.
        /// </summary>
        public static string ExperimentPanelHeader {
            get {
                return ResourceManager.GetString("ExperimentPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Stimulus Files (*.png;*.jpg)|*.png;*.jpg.
        /// </summary>
        public static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image Stimulus.
        /// </summary>
        public static string ImageStimulusTooltip {
            get {
                return ResourceManager.GetString("ImageStimulusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load.
        /// </summary>
        public static string LoadExperimentMenuItem {
            get {
                return ResourceManager.GetString("LoadExperimentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locator Definitions.
        /// </summary>
        public static string LocatorsPanelHeader {
            get {
                return ResourceManager.GetString("LocatorsPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string NewExperimentMenuItem {
            get {
                return ResourceManager.GetString("NewExperimentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point Locator.
        /// </summary>
        public static string PointLocatorTooltip {
            get {
                return ResourceManager.GetString("PointLocatorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Run Window.
        /// </summary>
        public static string RunWindowTitle {
            get {
                return ResourceManager.GetString("RunWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string SaveExperimentMenuItem {
            get {
                return ResourceManager.GetString("SaveExperimentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the session type.
        /// </summary>
        public static string StartupDialogTitle {
            get {
                return ResourceManager.GetString("StartupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Definitions.
        /// </summary>
        public static string StimulusPanelHeader {
            get {
                return ResourceManager.GetString("StimulusPanelHeader", resourceCulture);
            }
        }
    }
}
