//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    public sealed partial class StringSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StringSettings defaultInstance = ((StringSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StringSettings())));
        
        public static StringSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid height for the image stimulus")]
        public string InvalidImageHeight {
            get {
                return ((string)(this["InvalidImageHeight"]));
            }
            set {
                this["InvalidImageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid width for the image stimulus")]
        public string InvalidImageWidth {
            get {
                return ((string)(this["InvalidImageWidth"]));
            }
            set {
                this["InvalidImageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid value for the stimulus count in the trial")]
        public string InvalidStimulusCount {
            get {
                return ((string)(this["InvalidStimulusCount"]));
            }
            set {
                this["InvalidStimulusCount"] = value;
            }
        }
    }
}
