//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyExpStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurPsyExpStrings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Header_Definitions {
            get {
                return ResourceManager.GetString("Header_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment.
        /// </summary>
        public static string Header_Experiment {
            get {
                return ResourceManager.GetString("Header_Experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Header_Layout {
            get {
                return ResourceManager.GetString("Header_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Header_LoadExperiment {
            get {
                return ResourceManager.GetString("Header_LoadExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locator Definitions.
        /// </summary>
        public static string Header_LocatorDefinitions {
            get {
                return ResourceManager.GetString("Header_LocatorDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Header_NewExperiment {
            get {
                return ResourceManager.GetString("Header_NewExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Header_SaveExperiment {
            get {
                return ResourceManager.GetString("Header_SaveExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Panel.
        /// </summary>
        public static string Header_SingleLayout {
            get {
                return ResourceManager.GetString("Header_SingleLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Panel.
        /// </summary>
        public static string Header_SplitLayout {
            get {
                return ResourceManager.GetString("Header_SplitLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Definitions.
        /// </summary>
        public static string Header_StimulusDefinitions {
            get {
                return ResourceManager.GetString("Header_StimulusDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design an Experiment.
        /// </summary>
        public static string Label_DesignExperiment {
            get {
                return ResourceManager.GetString("Label_DesignExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run an Experiment.
        /// </summary>
        public static string Label_RunExperiment {
            get {
                return ResourceManager.GetString("Label_RunExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Design Window.
        /// </summary>
        public static string Title_DesignWindow {
            get {
                return ResourceManager.GetString("Title_DesignWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Run Window.
        /// </summary>
        public static string Title_RunWindow {
            get {
                return ResourceManager.GetString("Title_RunWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Session Window.
        /// </summary>
        public static string Title_StartupDialog {
            get {
                return ResourceManager.GetString("Title_StartupDialog", resourceCulture);
            }
        }
    }
}
