//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyExpStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurPsyExpStrings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string Content_AddButton {
            get {
                return ResourceManager.GetString("Content_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Step(s).
        /// </summary>
        public static string Content_AddStep {
            get {
                return ResourceManager.GetString("Content_AddStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trial(s).
        /// </summary>
        public static string Content_AddTrial {
            get {
                return ResourceManager.GetString("Content_AddTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HurPsy Experiment Files (*.xml) |*.xml.
        /// </summary>
        public static string FileFilter_Experiment {
            get {
                return ResourceManager.GetString("FileFilter_Experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Stimulus Files (*.png;*.jpg)|*.png;*.jpg.
        /// </summary>
        public static string FileFilter_Image {
            get {
                return ResourceManager.GetString("FileFilter_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Definitions.
        /// </summary>
        public static string Header_ElementsPanel {
            get {
                return ResourceManager.GetString("Header_ElementsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Experiment.
        /// </summary>
        public static string Header_ExperimentMenu {
            get {
                return ResourceManager.GetString("Header_ExperimentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Blocks.
        /// </summary>
        public static string Header_ExperimentPanel {
            get {
                return ResourceManager.GetString("Header_ExperimentPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load.
        /// </summary>
        public static string Header_LoadExperimentMenuItem {
            get {
                return ResourceManager.GetString("Header_LoadExperimentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locator Definitions.
        /// </summary>
        public static string Header_LocatorPanel {
            get {
                return ResourceManager.GetString("Header_LocatorPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Header_NewExperimentMenuItem {
            get {
                return ResourceManager.GetString("Header_NewExperimentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Header_SaveExperimentMenuItem {
            get {
                return ResourceManager.GetString("Header_SaveExperimentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Definitions.
        /// </summary>
        public static string Header_StimulusPanel {
            get {
                return ResourceManager.GetString("Header_StimulusPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trial(s).
        /// </summary>
        public static string Title_AddTrialDialog {
            get {
                return ResourceManager.GetString("Title_AddTrialDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Design Window.
        /// </summary>
        public static string Title_DesignWindow {
            get {
                return ResourceManager.GetString("Title_DesignWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Run Window.
        /// </summary>
        public static string Title_RunWindow {
            get {
                return ResourceManager.GetString("Title_RunWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the session type.
        /// </summary>
        public static string Title_StartupDialog {
            get {
                return ResourceManager.GetString("Title_StartupDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Block.
        /// </summary>
        public static string Tooltip_AddBlock {
            get {
                return ResourceManager.GetString("Tooltip_AddBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image Stimulus.
        /// </summary>
        public static string Tooltip_AddImageStimulus {
            get {
                return ResourceManager.GetString("Tooltip_AddImageStimulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point Locator.
        /// </summary>
        public static string Tooltip_AddPointLocator {
            get {
                return ResourceManager.GetString("Tooltip_AddPointLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new trial.
        /// </summary>
        public static string Tooltip_AddTrial {
            get {
                return ResourceManager.GetString("Tooltip_AddTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items.
        /// </summary>
        public static string Tooltip_DeleteObject {
            get {
                return ResourceManager.GetString("Tooltip_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Object.
        /// </summary>
        public static string Tooltip_EditObject {
            get {
                return ResourceManager.GetString("Tooltip_EditObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Image Height.
        /// </summary>
        public static string Tooltip_ImageStimulusHeight {
            get {
                return ResourceManager.GetString("Tooltip_ImageStimulusHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Image Id.
        /// </summary>
        public static string Tooltip_ImageStimulusId {
            get {
                return ResourceManager.GetString("Tooltip_ImageStimulusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Image Preview.
        /// </summary>
        public static string Tooltip_ImageStimulusPreview {
            get {
                return ResourceManager.GetString("Tooltip_ImageStimulusPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Image Width.
        /// </summary>
        public static string Tooltip_ImageStimulusWidth {
            get {
                return ResourceManager.GetString("Tooltip_ImageStimulusWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change panel width.
        /// </summary>
        public static string Tooltip_ResizeSlider {
            get {
                return ResourceManager.GetString("Tooltip_ResizeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select object.
        /// </summary>
        public static string Tooltip_SelectObject {
            get {
                return ResourceManager.GetString("Tooltip_SelectObject", resourceCulture);
            }
        }
    }
}
