//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyExpStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurPsyExpStrings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment definition Files (*.xml) |*.xml.
        /// </summary>
        public static string Filter_ExperimentFiles {
            get {
                return ResourceManager.GetString("Filter_ExperimentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.png,*.jpg)|*.png;*.jpg.
        /// </summary>
        public static string Filter_ImageFiles {
            get {
                return ResourceManager.GetString("Filter_ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Block.
        /// </summary>
        public static string Header_AddBlock {
            get {
                return ResourceManager.GetString("Header_AddBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Stimulus.
        /// </summary>
        public static string Header_AddImageStimulus {
            get {
                return ResourceManager.GetString("Header_AddImageStimulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Locator.
        /// </summary>
        public static string Header_AddLocator {
            get {
                return ResourceManager.GetString("Header_AddLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Locator.
        /// </summary>
        public static string Header_AddPointLocator {
            get {
                return ResourceManager.GetString("Header_AddPointLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stimulus.
        /// </summary>
        public static string Header_AddStimulus {
            get {
                return ResourceManager.GetString("Header_AddStimulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Definitions.
        /// </summary>
        public static string Header_BlockDefinitions {
            get {
                return ResourceManager.GetString("Header_BlockDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Header_Definitions {
            get {
                return ResourceManager.GetString("Header_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment.
        /// </summary>
        public static string Header_Experiment {
            get {
                return ResourceManager.GetString("Header_Experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Header_Layout {
            get {
                return ResourceManager.GetString("Header_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Header_LoadExperiment {
            get {
                return ResourceManager.GetString("Header_LoadExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locator Definitions.
        /// </summary>
        public static string Header_LocatorDefinitions {
            get {
                return ResourceManager.GetString("Header_LocatorDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Header_NewExperiment {
            get {
                return ResourceManager.GetString("Header_NewExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Header_SaveExperiment {
            get {
                return ResourceManager.GetString("Header_SaveExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Header_SaveExperimentAs {
            get {
                return ResourceManager.GetString("Header_SaveExperimentAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Settings.
        /// </summary>
        public static string Header_SettingsPanel {
            get {
                return ResourceManager.GetString("Header_SettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulus Definitions.
        /// </summary>
        public static string Header_StimulusDefinitions {
            get {
                return ResourceManager.GetString("Header_StimulusDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Button Height.
        /// </summary>
        public static string Label_CommandButtonHeight {
            get {
                return ResourceManager.GetString("Label_CommandButtonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design an Experiment.
        /// </summary>
        public static string Label_DesignExperiment {
            get {
                return ResourceManager.GetString("Label_DesignExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string Label_FontSize {
            get {
                return ResourceManager.GetString("Label_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Image Height.
        /// </summary>
        public static string Label_IconImageHeight {
            get {
                return ResourceManager.GetString("Label_IconImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Trial.
        /// </summary>
        public static string Label_IsFixed {
            get {
                return ResourceManager.GetString("Label_IsFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location X.
        /// </summary>
        public static string Label_LocationX {
            get {
                return ResourceManager.GetString("Label_LocationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Y.
        /// </summary>
        public static string Label_LocationY {
            get {
                return ResourceManager.GetString("Label_LocationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Font Size.
        /// </summary>
        public static string Label_MenuFontSize {
            get {
                return ResourceManager.GetString("Label_MenuFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Shuffle Trials.
        /// </summary>
        public static string Label_MustShuffleTrials {
            get {
                return ResourceManager.GetString("Label_MustShuffleTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Label_OK {
            get {
                return ResourceManager.GetString("Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run an Experiment.
        /// </summary>
        public static string Label_RunExperiment {
            get {
                return ResourceManager.GetString("Label_RunExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Font Size.
        /// </summary>
        public static string Label_SmallFontSize {
            get {
                return ResourceManager.GetString("Label_SmallFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Time.
        /// </summary>
        public static string Label_StepTime {
            get {
                return ResourceManager.GetString("Label_StepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Width.
        /// </summary>
        public static string Label_VisualHeight {
            get {
                return ResourceManager.GetString("Label_VisualHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Height.
        /// </summary>
        public static string Label_VisualWidth {
            get {
                return ResourceManager.GetString("Label_VisualWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Design Window.
        /// </summary>
        public static string Title_DesignWindow {
            get {
                return ResourceManager.GetString("Title_DesignWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment Run Window.
        /// </summary>
        public static string Title_RunWindow {
            get {
                return ResourceManager.GetString("Title_RunWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Session Window.
        /// </summary>
        public static string Title_StartupDialog {
            get {
                return ResourceManager.GetString("Title_StartupDialog", resourceCulture);
            }
        }
    }
}
