//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurPsyLibStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurPsyLibStrings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The experiment could not be loaded from file!.
        /// </summary>
        public static string Error_ExperimentNotLoaded {
            get {
                return ResourceManager.GetString("Error_ExperimentNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index value is invalid!.
        /// </summary>
        public static string Error_InvalidIndex {
            get {
                return ResourceManager.GetString("Error_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Locator object is found with the given id: .
        /// </summary>
        public static string Error_InvalidLocatorId {
            get {
                return ResourceManager.GetString("Error_InvalidLocatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stimulus object is found with the given id: .
        /// </summary>
        public static string Error_InvalidStimulusId {
            get {
                return ResourceManager.GetString("Error_InvalidStimulusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension value cannot be negative!.
        /// </summary>
        public static string Error_NegativeDimensionValue {
            get {
                return ResourceManager.GetString("Error_NegativeDimensionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position value cannot be negative!.
        /// </summary>
        public static string Error_NegativePositionValue {
            get {
                return ResourceManager.GetString("Error_NegativePositionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time value cannot be negative!.
        /// </summary>
        public static string Error_NegativeTimeValue {
            get {
                return ResourceManager.GetString("Error_NegativeTimeValue", resourceCulture);
            }
        }
    }
}
